sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "11"

before_install:
  - travis_retry npm install

matrix:
  allow_failures:
  - node_js: "11"

script:
  - npm test

notifications:
  email:
    - travis@nodejitsu.com

